const SHOW_ON_DESKTOP = 3;
const SHOW_ON_TABLET = 2;
const SHOW_ON_MOBILE = 2;
const DESKTOP_POINT = 1150;
const TABLET_POINT = 700;
const SHORTS = 40;

export {
    SHOW_ON_DESKTOP,
    SHOW_ON_TABLET,
    SHOW_ON_MOBILE,
    DESKTOP_POINT,
    TABLET_POINT,
    SHORTS,
};